apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ucvec6a0a-nodejs-gitops
  description: This is GitOps manifest for ucvec6a0a-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ucvec6a0a-nodejs
    backstage.io/kubernetes-id: ucvec6a0a-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ucvec6a0a-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ucvec6a0a-nodejs
