apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ucvec6a0a-nodejs
  janus-idp.io/tekton: ucvec6a0a-nodejs
  backstage.io/kubernetes-id: ucvec6a0a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ucvec6a0a-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
